name: fzyr
version: 0.1.2
summary: A fuzzy(er) finder 🔎
description: |
  **fzyr** is a simple and fast fuzzy text search. It exists as both a Rust 
  library and a standalone executable. Basically fzr re-written in Rust.

confinement: strict

grade: stable

apps:
  fzyr:
    command: fzyr

parts:
  fzyr:
    source: ..
    plugin: rust
    build-attributes: [no-system-libraries]
